import { fontFamily } from "@/constants/Styles";
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'flex-start',
        alignItems: 'center',
        backgroundColor: '#fff',
        padding: 20,
        paddingTop: 40,
    },
    text: {
        fontSize: 24,
        color: '#333',
    },
    itemContainer: {
        backgroundColor: "#fff",
        borderRadius: 8,
        margin: 10,
        padding: 16,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 1,
        alignContent: "center",
        gap: 15,
    },
    headerChef: {
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
    },
    chefIcon: {
        color: "#fff",
        width: 40,
        height: 40,
        borderRadius: 30,
        fontWeight: "bold",
        fontSize: 20,
        textAlign: "center",
        lineHeight: 40,
    },
    chefName: {
        fontWeight: "bold",
        fontSize: 20,
    },
    chefSpeciality: {
        backgroundColor: "#f0f0f0",
        borderRadius: 5,
        fontSize: 12,
        color: "#666",
        fontFamily: fontFamily.regular,
        paddingHorizontal: 6,
        paddingVertical: 2,
        textAlign: "center",
        alignSelf: "flex-start",
    },
    itemDescription: {
        fontSize: 14,
        color: "#666",
        marginTop: 8,
        flexShrink: 1,
        lineHeight: 20,
    },
    pratoTitle: {
        fontWeight: "bold",
        alignSelf: "flex-start",
        fontSize: 17,
        color: "#434343",
        width: "90%",
        marginRight: 8,
    },
    pratoQtd: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        marginTop: 12,
        paddingHorizontal: 4,
    },
    quantitySection: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
    },
    quantityLabel: {
        fontSize: 14,
        color: "#666",
        fontWeight: "500",
    },
    pratoNumber: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "transparent",
        borderRadius: 20,
        paddingHorizontal: 0,
        paddingVertical: 0,
        minWidth: 0,
        justifyContent: "center",
        gap: 8,
    },
    qtdeTextButton: {
        color: "#E53935",
        fontSize: 18,
        fontWeight: "bold",
        textAlign: "center",
        padding: 0,
        margin: 0,
        lineHeight: 18,
    },
    qtdeButton: {
        width: 36,
        height: 36,
        borderRadius: 18,
        justifyContent: "center",
        alignItems: "center",
        marginHorizontal: 0,
        backgroundColor: "#fff",
        elevation: 2,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        padding: 0,
        borderWidth: 1,
        borderColor: "#e0e0e0",
        minHeight: 36,
        minWidth: 36,
    },
    qtdeText: {
        fontSize: 18,
        fontWeight: "bold",
        marginHorizontal: 0,
        minWidth: 22,
        textAlign: "center",
        backgroundColor: "transparent",
        color: "#222",
        marginLeft: 4,
        marginRight: 4,
    },
    priceSection: {
        alignItems: "flex-end",
        justifyContent: "center",
        minWidth: 80,
    },
    originalPrice: {
        fontSize: 12,
        color: "#999",
        textDecorationLine: "line-through",
        marginBottom: 2,
    },
    offerPrice: {
        fontSize: 16,
        fontWeight: "bold",
        color: "#12c902c1",
    },
    regularPrice: {
        fontSize: 16,
        fontWeight: "bold",
        color: "#333",
    },
    precoContainer: {
        alignItems: "flex-end",
        justifyContent: "center",
        minWidth: 80,
    },
    presentationContainer: {
        flexDirection: "row",
        alignItems: "flex-start",
        gap: 12,
        flex: 1,
    },
    titleSection: {
        flexDirection: "row",
        alignItems: "flex-start",
        justifyContent: "space-between",
        marginBottom: 4,
        width: "100%",
    },
    imagemContainer: {
        width: 70,
        height: 70,
        borderRadius: 35,
        backgroundColor: "#f0f0f0",
    },
    ofertaLabel: {
        backgroundColor: "#E53935",
        borderRadius: 6,
        paddingHorizontal: 8,
        paddingVertical: 4,
        alignSelf: 'flex-start',
        marginLeft: 42,
    },
    ofertaText: {
        color: "#fff",
        fontSize: 10,
        fontWeight: "bold",
        textAlign: "center",
    },
    TotalPagar: {
        fontWeight: "bold",
        fontSize: 16,
    },
    TotalPreco: {
        fontSize: 20,
        fontWeight: "bold",
    },
    TotalContainer: {
        padding: 20,
        backgroundColor: "#fff",
        borderTopWidth: 0.5,
        borderTopColor: "#e0e0e0",
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    TotalTextButton: {
        color: "#fff",
        fontSize: 16,
        fontWeight: "600",
    },
    TotalButton: {
        backgroundColor: "#E53935",
        borderRadius: 10,
        paddingHorizontal: 24,
        paddingVertical: 4,
        minHeight: 50,
        justifyContent: "center",
        alignItems: "center",
    },
    modalContainer: {
        backgroundColor: '#fff',
        margin: 20,
        borderRadius: 16,
        maxHeight: '80%',
        maxWidth: '95%',
        width: '95%',
    },
    modalHeader: {
        padding: 20,
        paddingBottom: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#333',
        textAlign: 'center',
    },
    modalSubtitle: {
        fontSize: 14,
        color: '#666',
        textAlign: 'center',
        marginTop: 4,
    },
    modalContent: {
        maxHeight: 300,
        paddingHorizontal: 20,
    },
    confirmationItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#f5f5f5',
    },
    confirmationItemInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    confirmationImage: {
        width: 50,
        height: 50,
        borderRadius: 25,
        marginRight: 12,
        backgroundColor: '#f0f0f0',
    },
    confirmationDetails: {
        flex: 1,
    },
    confirmationItemName: {
        fontSize: 16,
        fontWeight: '600',
        color: '#333',
    },
    confirmationItemQuantity: {
        fontSize: 14,
        color: '#666',
        marginTop: 2,
    },
    confirmationItemPrice: {
        fontSize: 14,
        color: '#E53935',
        fontWeight: '500',
        marginTop: 2,
    },
    confirmationItemTotal: {
        alignItems: 'flex-end',
    },
    confirmationItemTotalText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#333',
    },
    modalFooter: {
        padding: 20,
        borderTopWidth: 1,
        borderTopColor: '#f0f0f0',
    },
    modalTotalSection: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
        paddingVertical: 10,
        backgroundColor: '#f8f8f8',
        borderRadius: 8,
        paddingHorizontal: 16,
    },
    modalTotalLabel: {
        fontSize: 18,
        fontWeight: '600',
        color: '#333',
    },
    modalTotalValue: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#E53935',
    },
    modalButtons: {
        flexDirection: 'row',
        gap: 12,
        marginTop: 8,
    },
    modalCancelButton: {
        flex: 1,
        borderColor: '#E53935',
        borderWidth: 1,
        backgroundColor: '#fff',
        minHeight: 44,
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalConfirmButton: {
        flex: 1,
        backgroundColor: '#E53935',
        minHeight: 44,
        justifyContent: 'center',
        alignItems: 'center',
    },
});